baseURL = 'https://www.skicon.org/'
languageCode = 'en-us'
title = 'SkiCon'
theme = "hello-friend-ng"


[params]
    backgroundImage = "img/SkiCon-bg.jpeg"

[[menu.main]]
    identifier = "Conference"
    name       = "Conference"
    weight     = 10
