baseURL = 'https://skicon.github.io/'
languageCode = 'en-us'
title = 'SkiConNE'
theme = "hello-friend-ng"


[params]
    backgroundImage = "img/SkiCon-bg.jpeg"

[[menu.main]]
    identifier = "Conference"
    name       = "Conference"
    weight     = 10
