baseURL = 'https://skicon.github.io/'
languageCode = 'en-us'
title = 'SkiCon New England'
theme = "hello-friend-ng"


[params]
    backgroundImage = "img/SkiCon-bg.jpeg"

[[menu.main]]
    identifier = "Conference"
    name       = "Conference"
    weight     = 10

[[menu.main]]
    identifier = "Twitter"
    name       = "Twitter"
    url        = "https://x.com/SkiConNE"
    weight     = 40

